# Generated by Django 4.2.4 on 2023-08-31 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_history_delete_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name_plural': 'Histories'},
        ),
    ]
