# Generated by Django 4.2.4 on 2023-09-10 21:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_history_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='questions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=list, size=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='sources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=list, size=None),
            preserve_default=False,
        ),
    ]
